version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/frontend"
      - "/backend"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@solvro/config"
