services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

volumes:
  db-data: