name: Backend - CI

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Set up AdonisJS environment
        run: |
          cp .env.development .env
          node ace generate:key

      - name: Lint
        run: npm run lint
        if: always()

      - name: Format
        run: npm run format:check
        if: always()

      - name: Type check
        run: npm run typecheck
        if: always()

      - name: Run Test Build
        run: npm run build
        if: always()
