name: Frontend - CI

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Format check
        run: npm run format:check
        if: always()

      - name: Lint
        run: npm run lint
        if: always()

      - name: Type check
        run: npm run typecheck
        if: always()

      - name: Build
        run: npm run build
        env:
          USOS_CONSUMER_KEY: hello
          USOS_CONSUMER_SECRET: jello
          NEXT_PUBLIC_API_URL: http://localhost:3333
        if: always()

      - name: Find deadcode
        run: npm run knip
        if: always()
